CREATE TABLE IF NOT EXISTS COMPANY(
ID  INTEGER PRIMARY KEY
NAME TEXT,
JOB TEXT,
);
INSERT INTO COMPANY(ID,NAME,JOB)VALUES
(12957694,"DIANA","CEO"),
(65432189,"ANA","SENIOR MANAGER"),
(45342678,"ORTHER","MANAGER");

SELECT * FROM COMPANY;
SELECT FROM COMPANY WHERE NAME LIKE "A%" AND "OR%";
